services:
  tsgroonga:
    container_name: tsgroonga
    image: tsgroonga
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GROONGA_HOST: groonga
      GROONGA_PORT: 10041
      GROONGA_ENTRYPOINT: /d

  groonga:
    container_name: tsgroonga-groonga
    image: groonga/groonga:15.0.4-debian
    ports:
      - 20041:10041
    volumes:
      - ./groonga/log:/var/log/groonga
      - ./groonga/init:/var/lib/groonga/initialize
    environment:
      - GROONGA_DB=/tmp/db/db
