export enum QueryOperator {
    MATCH = ':@',
    PREFIX = ':^',
    SUFFIX = ':$',
    NEAR = '*N',
    NEAR_PHRASE = '*NP',
    ORDERED_NEAR_PHRASE = '*ONP',
    NEAR_PHRASE_PRODUCT = '*NPP',
    ORDERED_NEAR_PHRASE_PRODUCT = '*ONPP',
    EQUAL = ':',
    NOT_EQUAL = ':!',
    LESS_THAN = ':<',
    LESS_THAN_EQUAL = ':<=',
    GREATER_THAN = ':>',
    GREATER_THAN_EQUAL = ':>=',
    REGEX = ':~',
    OR = 'OR',
    AND = '+',
    AND_NOT = '-'
}
